workspace:
  base: /srv/app
  path: src/code.gitea.io/gitea

pipeline:
  test:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS: sqlite bindata
      GOPATH: /srv/app
    commands:
      - apk -U add openssh-client
      - make clean
      - make generate
      - make vet
      - make lint
      - make test
      - make build
    when:
      event: [ push, tag, pull_request ]

  test-mysql:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS: sqlite bindata
      GOPATH: /srv/app
    commands:
      - make test-mysql
    when:
      event: [ push ]

  test-pgsql:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS: sqlite bindata
      GOPATH: /srv/app
    commands:
      - make test-pgsql
    when:
      event: [ push ]

  updater:
    image: karalabe/xgo-latest:latest
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS: sqlite bindata
      GOPATH: /srv/app
    commands:
      - make release
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  coverage:
    image: plugins/coverage
    server: https://coverage.gitea.io
    when:
      event: [ push, tag, pull_request ]

  docker:
    image: plugins/docker
    repo: gitea/gitea
    tags: [ '${TAG}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: gitea/gitea
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  release:
    image: plugins/s3
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /gitea/master
    when:
      event: [ push ]
      branch: [ master ]

  release:
    image: plugins/s3
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /gitea/$$TAG
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  github:
    image: plugins/github-release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  gitter:
    image: plugins/gitter

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    when:
      event: [ push ]

  pgsql:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=test
    when:
      event: [ push ]
