language: go

go_import_path: code.gitea.io/gitea

go:
  - 1.6
  - 1.7

env:
  TAGS: cert sqlite pam miniwinsvc

before_install:
  - sudo apt-get install -y libpam-dev

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge

script:
  - make clean
  - make vet

  # - make lint

  - make test
  - make build
  - make accept

after_success:
  - ./test-coverage.sh
