name: Deploy DCS to Docker

on:
  push:
    branches:
      - master
      - release/dcs/v*
    tags:
      - v*-dcs

jobs:
  deploy-docker:
    name: Build & Deploy DCS to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.RELATIVE_GITEA_ROOT }}
          fetch-depth: 0
          lfs: true

      - name: SET DOCKER_TAGS from GITHUB_REF (will be branch or tag of push event)
        shell: bash
        run: |
          REF=`echo ${GITHUB_REF} | cut -d "/" -f3-`
          echo "REF=${REF}"
          DOCKER_TAGS="${REF//\//-}"
          if [[ "${REF}" == "v"*"-dcs" ]]; then
            PATCH_VERSION=${REF#v}
            MINOR_VERSION=`echo ${PATCH_VERSION%-dcs} | cut -f1,2 -d'.'`
            MAJOR_VERSION=`echo ${MINOR_VERSION%-dcs} | cut -f1 -d'.'`
            DOCKER_TAGS="${DOCKER_TAGS},latest-prod,${MAJOR_VERSION},${MINOR_VERSION},${PATCH_VERSION}"
          elif [[ "${REF}" == "master" ]]; then
            DOCKER_TAGS="${DOCKER_TAGS},latest,latest-dev"
          else
            VERSION=`echo ${REF} | cut -f3 -d'/'`
            VERSION=${VERSION#v}
            DOCKER_TAGS="${DOCKER_TAGS},beta,${VERSION}-beta,latest-${VERSION}"
          fi
          echo "DOCKER_TAGS: ${DOCKER_TAGS}"
          echo "::set-env name=DOCKER_TAGS::$DOCKER_TAGS"

      - name: Debug
        shell: bash
        run: |
          echo "GITHUB_REF:" ${GITHUB_REF}
          echo "DOCKER_TAGS:" ${{ env.DOCKER_TAGS }}

      - name: Publish DCS to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: unfoldingword/dcs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ${{ env.GITEA_ROOT }}
          dockerfile: Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
