name: Deploy DCS to Docker

on:
  push:
    branches:
      - master
      - release/dcs/v*
    tags:
      - v*-dcs

jobs:
  deploy-docker:
    name: Build & Deploy DCS to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.RELATIVE_GITEA_ROOT }}
          fetch-depth: 0
          lfs: true

      - uses: nelonoel/branch-name@v1

      - name: SET DOCKER_TAGS from BRANCH_NAME (will be branch or tag of push event)
        shell: bash
        run: |
          DOCKER_TAGS="${BRANCH_NAME}"
          if [[ "${BRANCH_NAME}" == "master" ]]; then
            DOCKER_TAGS="${DOCKER_TAGS},latest"
          fi
          echo "::set-env name=DOCKER_TAGS::$DOCKER_TAGS"
        working-directory: ${{ env.GITEA_ROOT }}

      - name: Debug
        shell: bash
        run: |
          echo "GITHUB_REF:" ${GITHUB_REF}
          echo "BRANCH_NAME:" ${BRANCH_NAME}
          echo "DOCKER_TAGS:" ${{ env.DOCKER_TAGS }}
        working-directory: ${{ env.GITEA_ROOT }}

      - name: Publish DCS to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: unfoldingword/dcs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ${{ env.GITEA_ROOT }}
          dockerfile: Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
